/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectedRouteRouteImport } from './routes/connected/route'
import { Route as IndexRouteImport } from './routes/index'

const ConnectedRouteRoute = ConnectedRouteRouteImport.update({
  id: '/connected',
  path: '/connected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connected': typeof ConnectedRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connected': typeof ConnectedRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connected': typeof ConnectedRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connected'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connected'
  id: '__root__' | '/' | '/connected'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectedRouteRoute: typeof ConnectedRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connected': {
      id: '/connected'
      path: '/connected'
      fullPath: '/connected'
      preLoaderRoute: typeof ConnectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectedRouteRoute: ConnectedRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
